# -*- coding: utf-8 -*-
"""EstruturasCondicionais2

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/105hKiQv5L0jSGBdB6snOYpNqw7mp4_WB
"""

# Estruturas condicionais 2

def Estruturas_Condicionais2():

  idade = 20
  sexo = "Feminino"

# Estrutura nested if - Estruturas condicionais dentro de outras estruturas condicionais para criar lógicas mais complexas.

  if idade >= 18:
      if sexo == "Feminino":
          print("Você é uma mulher maior de idade.")
      else:
          print("Você é um homem maior de idade.")
  else:
      print("Você é menor de idade.")

# Estrutura short-circuit - Os operadores lógicos "and" e "or" podem ser usados em estruturas condicionais para avaliar múltiplas condições e tomar decisões com base nesses resultados. 

  if idade >= 18 and sexo == "Feminino":
      print("Você é uma mulher maior de idade.")
  else:
      print("Você não é uma mulher maior de idade.")

# Estrutura ternary - Permite que você execute uma expressão condicional em uma única linha.

  mensagem = "Maior de idade" if idade >= 18 else "Menor de idade"
  print(mensagem)