# -*- coding: utf-8 -*-
"""FuncoesBasicas.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1RfRKxLvHNn1yGafr-scctmxQNoL22YMK
"""

# Código para funções básicas em Python

def funcoes_basicas():
  print("Olá, mundo!") # Exibir mensagem -> print()

  nome = input("Digite seu nome: ") # Entrada de dados -> input()

  print(len(nome)) # Retorna(len) o tamanho de nome -> len()

  print(type(nome))  # Retorna o tipo de nome. Ex: int, decimal, float, etc... -> type()

  nome = str(nome)  # Convertendo para string  -> int(), float(), str()

  mensagem = "Olá, meu nome é {}.".format(nome) # Realiza a formatação de strings substituindo campos marcados por chaves {} -> format():
  print(mensagem)  # Saída: "Olá, meu nome é s/n."]

  fatia = slice(4, 8) # (Primeiro elemento a ser incluído, Ultima elemento a ser incluído) -> slice()
  print(nome[fatia])  # Saída: "mun"

  print(isinstance(nome, int)) # Verifica se um objeto é uma instância de uma determinada class, saída de dados = false (sabemos que é do tipo string) -> isinstance()